//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waPruebaLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cursos()
        {
            this.actividad = new HashSet<actividad>();
            this.nota = new HashSet<nota>();
            this.seccion = new HashSet<seccion>();
        }
    
        public int cod_curso { get; set; }
        public Nullable<int> cod_carrera { get; set; }
        public Nullable<int> cod_ciclo { get; set; }
        public Nullable<int> cod_pensum { get; set; }
        public string nombre { get; set; }
        public Nullable<int> creditos { get; set; }
        public string prerequisitos { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual ciclo ciclo { get; set; }
        public virtual pensum pensum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actividad> actividad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nota> nota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seccion> seccion { get; set; }
    }
}
