//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waPruebaLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_seccion
    {
        public int cod_det_seccion { get; set; }
        public Nullable<int> cod_seccion { get; set; }
        public Nullable<int> cod_estudiante { get; set; }
        public Nullable<int> promovido { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual seccion seccion { get; set; }
    }
}
