//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waPruebaLogin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ctxPrueba : DbContext
    {
        public ctxPrueba()
            : base("name=ctxPrueba")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<ciclo> ciclo { get; set; }
        public virtual DbSet<cursos> cursos { get; set; }
        public virtual DbSet<pensum> pensum { get; set; }
        public virtual DbSet<actividad> actividad { get; set; }
        public virtual DbSet<catedratico> catedratico { get; set; }
        public virtual DbSet<det_seccion> det_seccion { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
        public virtual DbSet<nota> nota { get; set; }
        public virtual DbSet<seccion> seccion { get; set; }
    }
}
