//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waPrueba5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada
    {
        public int cod_entrada { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public string fec_publicacion { get; set; }
        public string autor { get; set; }
        public string meta { get; set; }
    }
}
