//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace waPrueba5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public factura()
        {
            this.det_factura = new HashSet<det_factura>();
        }
    
        public int cod_factura { get; set; }
        public Nullable<int> cod_cliente { get; set; }
        public Nullable<System.DateTime> fec_factura { get; set; }
        public string serie_factura { get; set; }
        public string descripcion { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<det_factura> det_factura { get; set; }
    }
}
